### ISSUE TITLE
scale_y_continuous not qualified

### ISSUE THREAD

**Issue by barrettk** [metrumresearchgroup/pmplots#66]
Im working on a package that imports pmplots functions. I run into the following error, despite importing all of pmplots (`@import pmplots`)
```
Warning: Error in scale_y_continuous: could not find function "scale_y_continuous"
```

The error specifically triggers during `dv_pred`, `dv_ipred`, and `res_pred`. After looking into the pmplots code, I think it's because `scale_y_continuous` is not qualified [here](https://github.com/metrumresearchgroup/pmplots/blob/develop/R/cont.R#L35-L36), where `scatt()` is used in the above functions. It appears it is qualified [here](https://github.com/metrumresearchgroup/pmplots/blob/develop/R/utils.R#L168), and I didnt see any specific imports to the function (i.e. `@importFrom ggplot2 scale_y_continuous`).

I only run into this issue when trying to install our new package (i.e it works with `devtools::load_all()`), so I have a hunch this is a legitimate bug that people usually dont run into because they've installed ggplot and arent depending on `pmplots` for a separate package

**Comment by kyleam** [comment]
Fixed by #67.
