### ISSUE TITLE
npde_hist smooth line missing in version 0.3.6

### ISSUE THREAD

**Issue by callistosp** [metrumresearchgroup/pmplots#74]
We recently updated some old code to use pmplots v0.3.6 instead of v0.3.3. When this was done the smooth line in `npde_hist` no longer appears. I reran the code using v0.3.5 and the line was there, so it appears to be due to either some change between these two versions or, more likely, an issue with another package on the 2023-01-25 MPN snapshot.

![00b1496a-28a6-44f4-aca6-e610af2e24b0](https://user-images.githubusercontent.com/16599788/216430056-cf245782-329a-4004-acd1-c737a52ad4fa.png)

**Comment by seth127** [comment]
Yep, I would bet this has something to do with the recent (minorly infamous) `ggplot2` change related to `linewidth`. 

It looks like [`npde_hist()`](https://github.com/metrumresearchgroup/pmplots/blob/5dc2a2d7677d7309563cef93d925275c13823e4c/R/res_hist.R#L47) ultimately filters through to `cont_hist()`, which [calls `add_density()`](https://github.com/metrumresearchgroup/pmplots/blob/5dc2a2d7677d7309563cef93d925275c13823e4c/R/hist.R#L41) to get that line, which... was [changed to accomodate that `ggplot2` release](https://github.com/metrumresearchgroup/pmplots/blame/7cfd75d53b8899c91acab8ec909b5727a575cd45/R/layer.R#L189).

I'm not sure if this is something we should change in `pmplots` or if it's part of another package, as @callistosp suspects, but we should definitely look into it and try to get a patch release out before the next MPN.

**Comment by kylebaron** [comment]
@callistosp - 
Thanks for the report. Can you try passing `add_density` through to force this to get drawn?

``` r
library(pmplots)
#> Loading required package: ggplot2

data <- pmplots_data_obs()

npde_hist(data, add_density = TRUE) + facet_wrap(~CPc)
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
```

![](https://i.imgur.com/WXAVo1p.png)

<sup>Created on 2023-02-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I think the name of those stats also changed and we were just checking for the wrong value there. 

Kyle
